apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-redis-pod
  labels:
    app: voting-app
    type: DB
spec:
  template:
    metadata:
      name: redis-DB
      labels:
        name: redis-pod
        app: voting-app
        type: DB
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containersPort: 6379
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod