apiVersion: apps/v1
kind: Deployment
metadata:
    name: deploy-votingapp-vote
    labels:
        app: voting-app
        type: frontend
spec:
    template:
        metadata:
          name: voting-app-vote
          labels:
            app: voting-app
            type: frontend
        spec:
          containers:
            - name: votingapp-image
              image: dockersamples/examplevotingapp_vote
              ports:
                - containersPort: 80
    replicas: 3
    selector:
        matchLabels:
            name: deploy-votingapp-vote
