apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    name: postgres-service
    app: voting-app
    type: DB
sepc:
  ports:
    - port: 5432 
      targetPort: 5432
  selector:
    name: postgres-pod