apiVersion: v1
kind: Pod
metadata:
  name: postgres-db
  labels:
    name: postgres-pod
    app: voting-app
    type: DB
spec:
  containers:
    - name: postgres
      image: postgres:9.4
      ports:
        - containerPort: 5432
