apiVersion: v1
kind: Pod
metadata:
  name: redis-db
  labels:
    name: redis-pod
    app: voting-app
    type: DB
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
