apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-service
    app: voting-app
    type: DB
spec:
  ports:
    - port: 6372 
      targetPort: 6372
  selector:
    name: redis-pod
