apiVersion: v1
kind: Pod
metadata:
  name: voting-app-result
  labels:
    name: voting-app-result
    app: voting-app
    type: frontend
spec:
  containers:
    - name: votingapp_result-image
      image: dockersamples/examplevotingapp_result
      ports:
      - containersPort: 80