apiVersion: v1
kind: Pod
metadata:
    name: voting-app-worker
    labels:
        name: voting-app-worker
        app: voting-app
        type: worker-pod
spec:
    containers:
        - name: votingapp-worker-image
          image: dockersamples/examplevotingapp_worker
          

  