apiVersion: v1
kind: Pod
metadata:
  name: voting-app-vote
  labels:
    name: voting-app-vote
    app: voting-app
    type: frontend
spec:
  containers:
    - name: votingapp-image
      image: dockersamples/examplevotingapp_vote
      ports:
        - containersPort: 80